version: '2'
services:
  dersx-app:
    image: dersx
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://dersx-mysql:3306/dersx?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://dersx-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://dersx-elasticsearch:9200
    ports:
      - 8080:8080
  dersx-mysql:
    extends:
      file: mysql.yml
      service: dersx-mysql
  dersx-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: dersx-elasticsearch
